version: "3.9"
services:
  app:
    build: .
    container_name: fleet_app
    ports:
      - "8090:8090"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fleet_management
      DB_SSLMODE: disable
      MQTT_BROKER: fleet_mqtt
      MQTT_PORT: 1883
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_HOST: fleet_rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - db
      - rabbitmq
      - mqtt
    restart: always


  db:
    image: postgres:15
    container_name: fleet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleet_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fleet_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mqtt:
    image: eclipse-mosquitto:2
    container_name: fleet_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log


volumes:
  pgdata:
  mosquitto_data:
  mosquitto_log:
